apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}
spec:
  selector:
    app: {{ .Release.Name}}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.targetPort }}
  type: {{  .Values.app.service.type }}